version: "2"

services:
 pushgateway:
  image: prom/pushgateway
  ports:
   - "9091:9091"

 prometheus:
  image: prom/prometheus
  depends_on:
   - "pushgateway"
  volumes:
   - "prometheus-data:/prometheus"
   - "./prometheus.yml:/etc/prometheus/prometheus.yml"

 grafana:
  image: grafana/grafana
  ports:
   - "3000:3000"
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=enter
  depends_on:
   - prometheus
  volumes:
   - "grafana-data:/var/lib/grafana"
   - "./grafana.ini:/etc/grafana/grafana.ini"

volumes:
  grafana-data:
  prometheus-data:
